preset: laravel
enabled:
  - align_double_arrow
  - align_equals
disabled:
  - array_indentation
  - no_unused_imports
  - not_operator_with_successor_space
  - trailing_comma_in_multiline_array
  - unalign_equals
finder:
  not-name:
    - index.php
    - server.php