codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "app/Http/Controllers/Auth"
  - "app/Http/Middleware/Authenticate.php"
  - "app/Http/Middleware/RedirectIfAuthenticated.php"
  - "app/Http/Middleware/TrustHosts.php"
  - "app/Providers/AppServiceProvider.php"
  - "app/Providers/AuthServiceProvider.php"
  - "app/Providers/BroadcastServiceProvider.php"
  - "app/Providers/EventServiceProvider.php"
  - "app/Providers/RouteServiceProvider.php"
  - "app/Exceptions/Handler.php"